#if UNITY_EDITOR
using System;
using System.IO;
using System.Text;

namespace YokiFrame.TableKit.Editor
{
    /// <summary>
    /// TableKitCodeGenerator - 浠ｇ爜妯℃澘鐢熸垚
    /// </summary>
    public static partial class TableKitCodeGenerator
    {
        /// <summary>
        /// 鐢熸垚 TableKit.cs 涓绘枃浠?
        /// </summary>
        private static void GenerateTableKit(string outputDir, string tablesNamespace, bool hasYokiFrame,
            string runtimePathPattern, string editorDataPath,
            bool useAsyncLoading = false, string[] tableFileNames = null)
        {
            // 杞箟璺緞涓殑鐗规畩瀛楃
            var escapedRuntimePath = runtimePathPattern.Replace("\\", "\\\\").Replace("\"", "\\\"");
            var escapedEditorPath = editorDataPath.Replace("\\", "\\\\").Replace("\"", "\\\"");

            var sb = new StringBuilder();
            AppendTableKitHeader(sb, tablesNamespace, escapedRuntimePath, useAsyncLoading);
            AppendTableKitLoaderSetters(sb);
            AppendTableKitInit(sb, tablesNamespace);
            AppendTableKitLoadMethods(sb);
            AppendDefaultLoaders(sb, hasYokiFrame);
            if (useAsyncLoading)
            {
                AppendAsyncLoadingSection(sb, tablesNamespace, hasYokiFrame, tableFileNames);
            }
            AppendTableKitReloadAndClear(sb, useAsyncLoading);
            AppendTableKitEditorSection(sb, tablesNamespace, escapedEditorPath);
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputDir, "TableKit.cs"), sb.ToString(), Encoding.UTF8);
        }

        private static void AppendTableKitHeader(StringBuilder sb, string tablesNamespace, string escapedRuntimePath,
            bool useAsyncLoading)
        {
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by YokiFrame TableKit.");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Reflection;");
            if (useAsyncLoading)
            {
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using System.Threading;");
            }
            sb.AppendLine("using Luban;");
            sb.AppendLine("using UnityEngine;");
            if (useAsyncLoading)
            {
                sb.AppendLine("#if YOKIFRAME_UNITASK_SUPPORT");
                sb.AppendLine("using Cysharp.Threading.Tasks;");
                sb.AppendLine("#endif");
            }
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// 閰嶇疆琛ㄧ郴缁熷叆鍙ｇ被");
            sb.AppendLine("/// 鐢?TableKit 宸ュ叿鑷姩鐢熸垚锛岃矾寰勯厤缃凡宓屽叆浠ｇ爜");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public static class TableKit");
            sb.AppendLine("{");
            sb.AppendLine($"    private static {tablesNamespace}.Tables sTables;");
            sb.AppendLine("    private static Func<string, byte[]> sBinaryLoader;");
            sb.AppendLine("    private static Func<string, string> sJsonLoader;");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 鏄惁宸插垵濮嬪寲");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static bool Initialized { get; private set; }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 杩愯鏃惰矾寰勬ā寮忥紙鐢熸垚鏃跺祵鍏ワ級");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static string RuntimePathPattern {{ get; set; }} = \"{escapedRuntimePath}\";");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Gets the loaded table instance.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static {tablesNamespace}.Tables Tables");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            if (sTables == null) Init();");
            sb.AppendLine("            return sTables;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static void AppendTableKitLoaderSetters(StringBuilder sb)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 璁剧疆浜岃繘鍒舵暟鎹姞杞藉櫒");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void SetBinaryLoader(Func<string, byte[]> loader)");
            sb.AppendLine("    {");
            sb.AppendLine("        sBinaryLoader = loader ?? throw new ArgumentNullException(nameof(loader));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Sets the JSON data loader.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void SetJsonLoader(Func<string, string> loader)");
            sb.AppendLine("    {");
            sb.AppendLine("        sJsonLoader = loader ?? throw new ArgumentNullException(nameof(loader));");
            sb.AppendLine("    }");
        }

        private static void AppendTableKitInit(StringBuilder sb, string tablesNamespace)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 鍒濆鍖栭厤缃〃");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void Init()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (Initialized) return;");
            sb.AppendLine();
            sb.AppendLine("        if (sBinaryLoader == null) sBinaryLoader = DefaultBinaryLoader;");
            sb.AppendLine("        if (sJsonLoader == null) sJsonLoader = DefaultJsonLoader;");
            sb.AppendLine();
            sb.AppendLine($"        var tablesCtor = typeof({tablesNamespace}.Tables).GetConstructors()[0];");
            sb.AppendLine("        var loaderReturnType = tablesCtor.GetParameters()[0].ParameterType.GetGenericArguments()[1];");
            sb.AppendLine();
            sb.AppendLine("        object loader = loaderReturnType == typeof(ByteBuf)");
            sb.AppendLine("            ? new Func<string, ByteBuf>(LoadBinary)");
            sb.AppendLine("            : CreateJsonLoader(loaderReturnType);");
            sb.AppendLine();
            sb.AppendLine($"        sTables = ({tablesNamespace}.Tables)tablesCtor.Invoke(new object[] {{ loader }});");
            sb.AppendLine("        Initialized = true;");
            sb.AppendLine("    }");
        }

        private static void AppendTableKitLoadMethods(StringBuilder sb)
        {
            sb.AppendLine();
            sb.AppendLine("    private static MethodInfo sJsonParseMethod;");
            sb.AppendLine();
            sb.AppendLine("    private static object CreateJsonLoader(Type jsonNodeType)");
            sb.AppendLine("    {");
            sb.AppendLine("        var funcType = typeof(Func<,>).MakeGenericType(typeof(string), jsonNodeType);");
            sb.AppendLine("        var loadJsonMethod = typeof(TableKit).GetMethod(nameof(LoadJsonDynamic),");
            sb.AppendLine("            BindingFlags.NonPublic | BindingFlags.Static);");
            sb.AppendLine("        return Delegate.CreateDelegate(funcType, loadJsonMethod);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static object LoadJsonDynamic(string fileName)");
            sb.AppendLine("    {");
            sb.AppendLine("        var json = sJsonLoader(fileName);");
            sb.AppendLine("        if (string.IsNullOrEmpty(json))");
            sb.AppendLine("        {");
            sb.AppendLine("            Debug.LogError($\"[TableKit] 鍔犺浇閰嶇疆琛ㄥけ璐? {fileName}\");");
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        if (sJsonParseMethod == null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var jsonType = AppDomain.CurrentDomain.GetAssemblies()");
            sb.AppendLine("                .Where(a => !a.IsDynamic)");
            sb.AppendLine("                .SelectMany(a => { try { return a.GetTypes(); } catch { return Type.EmptyTypes; } })");
            sb.AppendLine("                .FirstOrDefault(t => t.FullName == \"Luban.SimpleJson.JSON\" || t.FullName == \"SimpleJSON.JSON\");");
            sb.AppendLine();
            sb.AppendLine("            if (jsonType == null)");
            sb.AppendLine("                throw new InvalidOperationException(\"鏃犳硶鎵惧埌 JSON 绫诲瀷\");");
            sb.AppendLine();
            sb.AppendLine("            sJsonParseMethod = jsonType.GetMethod(\"Parse\", BindingFlags.Public | BindingFlags.Static,");
            sb.AppendLine("                null, new[] { typeof(string) }, null);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        return sJsonParseMethod.Invoke(null, new object[] { json });");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static ByteBuf LoadBinary(string fileName)");
            sb.AppendLine("    {");
            sb.AppendLine("        var bytes = sBinaryLoader(fileName);");
            sb.AppendLine("        if (bytes == null || bytes.Length == 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            Debug.LogError($\"[TableKit] 鍔犺浇閰嶇疆琛ㄥけ璐? {fileName}\");");
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine("        return new ByteBuf(bytes);");
            sb.AppendLine("    }");
        }

        private static void AppendDefaultLoaders(StringBuilder sb, bool hasYokiFrame)
        {
            sb.AppendLine();
            sb.AppendLine("    #region Default Loaders");
            sb.AppendLine();

            if (hasYokiFrame)
            {
                sb.AppendLine("    // 榛樿鍔犺浇鍣細浣跨敤 YokiFrame.ResKit");
                sb.AppendLine("    private static byte[] DefaultBinaryLoader(string fileName)");
                sb.AppendLine("    {");
                sb.AppendLine("        var path = string.Format(RuntimePathPattern, fileName);");
                sb.AppendLine("        var handler = YokiFrame.ResKit.LoadAsset<TextAsset>(path);");
                sb.AppendLine("        if (handler == null)");
                sb.AppendLine("        {");
                sb.AppendLine("            Debug.LogError($\"[TableKit] ResKit 鍔犺浇澶辫触: {path}\");");
                sb.AppendLine("            return null;");
                sb.AppendLine("        }");
                sb.AppendLine("        var textAsset = handler.Asset as TextAsset;");
                sb.AppendLine("        var bytes = textAsset != null ? textAsset.bytes : null;");
                sb.AppendLine("        handler.Release();");
                sb.AppendLine("        return bytes;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    private static string DefaultJsonLoader(string fileName)");
                sb.AppendLine("    {");
                sb.AppendLine("        var path = string.Format(RuntimePathPattern, fileName);");
                sb.AppendLine("        var handler = YokiFrame.ResKit.LoadAsset<TextAsset>(path);");
                sb.AppendLine("        if (handler == null)");
                sb.AppendLine("        {");
                sb.AppendLine("            Debug.LogError($\"[TableKit] ResKit 鍔犺浇澶辫触: {path}\");");
                sb.AppendLine("            return null;");
                sb.AppendLine("        }");
                sb.AppendLine("        var textAsset = handler.Asset as TextAsset;");
                sb.AppendLine("        var text = textAsset != null ? textAsset.text : null;");
                sb.AppendLine("        handler.Release();");
                sb.AppendLine("        return text;");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine("    // 榛樿鍔犺浇鍣細浣跨敤 Resources");
                sb.AppendLine("    private static byte[] DefaultBinaryLoader(string fileName)");
                sb.AppendLine("    {");
                sb.AppendLine("        var path = string.Format(RuntimePathPattern, fileName);");
                sb.AppendLine("        var asset = Resources.Load<TextAsset>(path);");
                sb.AppendLine("        return asset != null ? asset.bytes : null;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    private static string DefaultJsonLoader(string fileName)");
                sb.AppendLine("    {");
                sb.AppendLine("        var path = string.Format(RuntimePathPattern, fileName);");
                sb.AppendLine("        var asset = Resources.Load<TextAsset>(path);");
                sb.AppendLine("        return asset != null ? asset.text : null;");
                sb.AppendLine("    }");
            }
            
            sb.AppendLine();
            sb.AppendLine("    #endregion");
        }

        private static void AppendTableKitReloadAndClear(StringBuilder sb, bool useAsyncLoading)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Reloads all table data.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void Reload(Action onComplete = null)");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            sTables = null;");
            sb.AppendLine("            Initialized = false;");
            sb.AppendLine("            Init();");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (Exception ex)");
            sb.AppendLine("        {");
            sb.AppendLine("            Debug.LogError($\"[TableKit] Reload failed: {ex.Message}\");");
            sb.AppendLine("        }");
            sb.AppendLine("        onComplete?.Invoke();");
            sb.AppendLine("    }");

            if (useAsyncLoading)
            {
                sb.AppendLine();
                sb.AppendLine("#if YOKIFRAME_UNITASK_SUPPORT");
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    /// Reloads all table data asynchronously.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static async UniTask ReloadAsync(CancellationToken cancellationToken = default)");
                sb.AppendLine("    {");
                sb.AppendLine("        sTables = null;");
                sb.AppendLine("        Initialized = false;");
                sb.AppendLine("        await InitAsync(cancellationToken);");
                sb.AppendLine("    }");
                sb.AppendLine("#endif");
            }

            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Clears all loaded table data.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void Clear()");
            sb.AppendLine("    {");
            sb.AppendLine("        sTables = null;");
            sb.AppendLine("        Initialized = false;");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("        sTablesEditor = null;");
            sb.AppendLine("#endif");
            sb.AppendLine("    }");
        }

        private static void AppendTableKitEditorSection(StringBuilder sb, string tablesNamespace, string escapedEditorPath)
        {
            sb.AppendLine();
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine($"    private static {tablesNamespace}.Tables sTablesEditor;");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 缂栬緫鍣ㄦ暟鎹矾寰勶紙鐢熸垚鏃跺祵鍏ワ級");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static string EditorDataPath {{ get; set; }} = \"{escapedEditorPath}\";");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 鑾峰彇缂栬緫鍣ㄦā寮忎笅鐨勯厤缃〃瀹炰緥");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static {tablesNamespace}.Tables TablesEditor");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            if (sTablesEditor == null) InitEditor();");
            sb.AppendLine("            return sTablesEditor;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static void InitEditor()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (sTablesEditor != null) return;");
            sb.AppendLine();
            sb.AppendLine($"        var tablesCtor = typeof({tablesNamespace}.Tables).GetConstructors()[0];");
            sb.AppendLine("        var loaderReturnType = tablesCtor.GetParameters()[0].ParameterType.GetGenericArguments()[1];");
            sb.AppendLine();
            sb.AppendLine("        object loader = loaderReturnType == typeof(ByteBuf)");
            sb.AppendLine("            ? new Func<string, ByteBuf>(LoadBinaryEditor)");
            sb.AppendLine("            : CreateJsonLoaderEditor(loaderReturnType);");
            sb.AppendLine();
            sb.AppendLine($"        sTablesEditor = ({tablesNamespace}.Tables)tablesCtor.Invoke(new object[] {{ loader }});");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static object CreateJsonLoaderEditor(Type jsonNodeType)");
            sb.AppendLine("    {");
            sb.AppendLine("        var funcType = typeof(Func<,>).MakeGenericType(typeof(string), jsonNodeType);");
            sb.AppendLine("        var loadJsonMethod = typeof(TableKit).GetMethod(nameof(LoadJsonEditorDynamic),");
            sb.AppendLine("            BindingFlags.NonPublic | BindingFlags.Static);");
            sb.AppendLine("        return Delegate.CreateDelegate(funcType, loadJsonMethod);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static object LoadJsonEditorDynamic(string fileName)");
            sb.AppendLine("    {");
            sb.AppendLine("        var path = $\"{EditorDataPath}{fileName}.json\";");
            sb.AppendLine("        var asset = UnityEditor.AssetDatabase.LoadAssetAtPath<TextAsset>(path);");
            sb.AppendLine("        if (asset == null)");
            sb.AppendLine("        {");
            sb.AppendLine("            Debug.LogError($\"[TableKit] 缂栬緫鍣ㄥ姞杞介厤缃〃澶辫触: {path}\");");
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        if (sJsonParseMethod == null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var jsonType = AppDomain.CurrentDomain.GetAssemblies()");
            sb.AppendLine("                .Where(a => !a.IsDynamic)");
            sb.AppendLine("                .SelectMany(a => { try { return a.GetTypes(); } catch { return Type.EmptyTypes; } })");
            sb.AppendLine("                .FirstOrDefault(t => t.FullName == \"Luban.SimpleJson.JSON\" || t.FullName == \"SimpleJSON.JSON\");");
            sb.AppendLine();
            sb.AppendLine("            if (jsonType == null)");
            sb.AppendLine("                throw new InvalidOperationException(\"鏃犳硶鎵惧埌 JSON 绫诲瀷\");");
            sb.AppendLine();
            sb.AppendLine("            sJsonParseMethod = jsonType.GetMethod(\"Parse\", BindingFlags.Public | BindingFlags.Static,");
            sb.AppendLine("                null, new[] { typeof(string) }, null);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        return sJsonParseMethod.Invoke(null, new object[] { asset.text });");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static ByteBuf LoadBinaryEditor(string fileName)");
            sb.AppendLine("    {");
            sb.AppendLine("        var path = $\"{EditorDataPath}{fileName}.bytes\";");
            sb.AppendLine("        var asset = UnityEditor.AssetDatabase.LoadAssetAtPath<TextAsset>(path);");
            sb.AppendLine("        if (asset == null)");
            sb.AppendLine("        {");
            sb.AppendLine("            Debug.LogError($\"[TableKit] 缂栬緫鍣ㄥ姞杞介厤缃〃澶辫触: {path}\");");
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine("        return new ByteBuf(asset.bytes);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Refreshes the editor-side table cache.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void RefreshEditor() => sTablesEditor = null;");
            sb.AppendLine("#endif");
        }

        /// <summary>
        /// 鐢熸垚寮傛鍔犺浇浠ｇ爜鍖哄潡
        /// </summary>
    }
}
#endif
