using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;

namespace YokiFrame
{
    public class UICodeGenTemplate
    {
        /// <summary>
        /// 头部注释
        /// </summary>
        private static void WriteAutoGeneratedHeader(RootCode rootCode)
        {
            var now = DateTime.Now;
            var timestamp = now.ToString("yyyy-MM-dd HH:mm:ss");
            rootCode
                .Custom("//------------------------------------------------------------------------------")
                .Custom("// <auto-generated>")
                .Custom("//     This code was generated by YokiFrame UIKit.")
                .Custom($"//     Generated at: {timestamp}")
                .Custom("//")
                .Custom("//     Changes to this file may cause incorrect behavior and will be lost if")
                .Custom("//     the code is regenerated.")
                .Custom("// </auto-generated>")
                .Custom("//------------------------------------------------------------------------------")
                .EmptyLine();
        }

        #region PanelCodeTemplate
        /// <summary>
        /// UI面板代码模板
        /// </summary>
        /// <param name="name">面板名称</param>
        /// <param name="scriptFilePath">代码路径</param>
        /// <param name="scriptNamespace">命名空间</param>
        /// <param name="options">代码生成选项</param>
        public static void WritePanel(string name, string scriptFilePath, string scriptNamespace, PanelCodeGenOptions options = null)
        {
            if (File.Exists(scriptFilePath)) return;

            options ??= new PanelCodeGenOptions();

            var writer = File.CreateText(scriptFilePath);
            var codeWriter = new FileCodeWriteKit(writer);
            var rootCode = new RootCode()
                .Using(nameof(UnityEngine))
                .Using("UnityEngine.UI")
                .Using(nameof(YokiFrame))
                .EmptyLine()
                .Namespace(scriptNamespace, scope =>
                {
                    var DataName = $"{name}Data";
                    scope
                    .Class(DataName, nameof(IUIData), false, false, classScope => { })
                    .Class(name, nameof(UIPanel), true, false, classScope =>
                    {
                        // OnInit
                        classScope
                        .CustomScope($"protected override void OnInit({nameof(IUIData)} uiData = null)", false, function =>
                        {
                            function
                            .Custom($"mData = uiData as {DataName} ?? new {DataName}();")
                            .Custom("// 在此添加初始化代码");
                        })
                        .EmptyLine();

                        // OnOpen
                        classScope
                        .CustomScope($"protected override void OnOpen({nameof(IUIData)} uiData = null)", false, function =>
                        {
                            function
                            .Custom($"mData = uiData as {DataName} ?? mData;");
                        })
                        .EmptyLine();

                        // OnShow
                        classScope
                        .CustomScope("protected override void OnShow()", false, function => { })
                        .EmptyLine();

                        // OnHide
                        classScope
                        .CustomScope("protected override void OnHide()", false, function => { })
                        .EmptyLine();

                        // OnClose
                        classScope
                        .CustomScope("protected override void OnClose()", false, function => { });

                        // 生成新的生命周期钩子
                        if (options.GenerateLifecycleHooks)
                        {
                            classScope.EmptyLine();
                            classScope.Custom("#region 生命周期钩子");
                            classScope.EmptyLine();

                            // OnWillShow
                            classScope
                            .CustomScope("protected override void OnWillShow()", false, function =>
                            {
                                function.Custom("// 面板即将显示时调用");
                            })
                            .EmptyLine();

                            // OnDidShow
                            classScope
                            .CustomScope("protected override void OnDidShow()", false, function =>
                            {
                                function.Custom("// 面板显示完成后调用");
                            })
                            .EmptyLine();

                            // OnWillHide
                            classScope
                            .CustomScope("protected override void OnWillHide()", false, function =>
                            {
                                function.Custom("// 面板即将隐藏时调用");
                            })
                            .EmptyLine();

                            // OnDidHide
                            classScope
                            .CustomScope("protected override void OnDidHide()", false, function =>
                            {
                                function.Custom("// 面板隐藏完成后调用");
                            })
                            .EmptyLine();

                            // OnFocus
                            classScope
                            .CustomScope("protected override void OnFocus()", false, function =>
                            {
                                function.Custom("// 面板获得焦点时调用");
                            })
                            .EmptyLine();

                            // OnBlur
                            classScope
                            .CustomScope("protected override void OnBlur()", false, function =>
                            {
                                function.Custom("// 面板失去焦点时调用");
                            })
                            .EmptyLine();

                            // OnResume
                            classScope
                            .CustomScope("protected override void OnResume()", false, function =>
                            {
                                function.Custom("// 面板从栈中恢复时调用");
                            });

                            classScope.EmptyLine();
                            classScope.Custom("#endregion");
                        }

                        // 生成焦点支持
                        if (options.GenerateFocusSupport)
                        {
                            classScope.EmptyLine();
                            classScope.Custom("#region 焦点导航");
                            classScope.EmptyLine();

                            classScope
                            .CustomScope("protected override GameObject GetDefaultFocusTarget()", false, function =>
                            {
                                function.Custom("// 返回默认焦点目标，返回 null 则不自动设置焦点");
                                function.Custom("return null;");
                            });

                            classScope.EmptyLine();
                            classScope.Custom("#endregion");
                        }
                    });
                });
            rootCode.Gen(codeWriter);
            codeWriter.Dispose();
        }
        /// <summary>
        /// 面板定义代码模板
        /// </summary>
        /// <param name="name">面板名称</param>
        /// <param name="designerPath">定义路径</param>
        /// <param name="scriptNamespace">命名空间</param>
        /// <param name="bindCodeInfo">绑定信息</param>
        public static void WritePanelDesigner(string name, string designerPath, string scriptNamespace, BindCodeInfo bindCodeInfo)
        {
            var codeContext = new UIGenCodeContext
            {
                PanelName = name,
                ElementPath = $"{UIKitCreateConfig.Instance.ScriptGeneratePath}/{name}/{nameof(UIElement)}",
                ComponentPath = $"{UIKitCreateConfig.Instance.ScriptGeneratePath}/{nameof(UIComponent)}",
                ScriptNamespace = scriptNamespace,
            };

            var writer = File.CreateText(designerPath);
            var codeWriter = new FileCodeWriteKit(writer);
            var root = new RootCode();
            WriteAutoGeneratedHeader(root);
            root
                .Using(nameof(System))
                .Using(nameof(UnityEngine))
                .Using("UnityEngine.UI")
                .Using(nameof(YokiFrame))
                .EmptyLine()
                .Namespace(scriptNamespace, scope =>
                {
                    scope.Custom($"// Generate Id:{Guid.NewGuid()}");
                    scope.Class(name, string.Empty, true, false, classScope =>
                    {
                        // 根据order排序
                        var sortList = bindCodeInfo.MemberDic.Values.OrderBy(info => info.order).ToList();
                        foreach (var bindInfo in sortList)
                        {
                            if (bindInfo.RepeatElement) continue;
                            if (!string.IsNullOrEmpty(bindInfo.Comment))
                            {
                                classScope.Custom("/// <summary>");
                                classScope.Custom("/// " + bindInfo.Comment);
                                classScope.Custom("/// </summary>");
                            }
                            classScope.Custom("[SerializeField]");
                            var typeName = $"{(bindInfo.Bind is BindType.Element ? $"{scriptNamespace}.{name}{nameof(UIElement)}." : "")}{bindInfo.Type}";
                            classScope.Custom($"public {typeName} {bindInfo.Name};");

                            RecursionGen(bindInfo, codeContext);
                        }
                        classScope.EmptyLine();

                        classScope.CustomScope("protected override void ClearUIComponents()", false, (function) =>
                        {
                            foreach (var bindInfo in bindCodeInfo.MemberDic.Values)
                            {
                                if (bindInfo.RepeatElement) continue;
                                if (bindInfo.Bind is BindType.Element or BindType.Component)
                                {
                                    function.Custom($"{bindInfo.Name}.Clear();");
                                }
                                function.Custom($"{bindInfo.Name} = default;");
                            }

                            function.EmptyLine();
                            function.Custom("mData = null;");
                        });

                        classScope.EmptyLine();
                        classScope.Custom($"{name}Data mData;");
                        classScope.CustomScope($"public {name}Data Data", false, (property) =>
                        {
                            property.CustomScope("get", false, (getter) => { getter.Custom("return mData;"); });
                        });
                    });
                });
            root.Gen(codeWriter);
            codeWriter.Dispose();
        }
        #endregion

        #region ElementCodeTemplate
        /// <summary>
        /// UI组件元素代码模板
        /// </summary>
        public static void WriteElement(BindCodeInfo bindCodeInfo, UIGenCodeContext codeContext)
        {
            var name = bindCodeInfo.Type;
            var scriptFilePath = codeContext.ElementPath + $"/{name}.cs";
            if (!File.Exists(scriptFilePath))
            {
                Directory.CreateDirectory(PathUtils.GetDirectoryPath(scriptFilePath));
                var writer = File.CreateText(scriptFilePath);
                var codeWriter = new FileCodeWriteKit(writer);
                var rootCode = new RootCode()
                    .Custom("/****************************************************************************")
                    .Custom($"{DateTime.Now.Year}.{DateTime.Now.Month} {SystemInfo.deviceName}")
                    .Custom("****************************************************************************/")
                    .EmptyLine()
                    .Using(nameof(UnityEngine))
                    .Using("UnityEngine.UI")
                    .Using(nameof(YokiFrame))
                    .EmptyLine()
                    .Namespace($"{codeContext.ScriptNamespace}.{codeContext.PanelName}{nameof(UIElement)}", scope =>
                    {
                        scope.Class(name, nameof(UIElement), true, false, classScope =>
                        {

                        });
                    });

                rootCode.Gen(codeWriter);
                codeWriter.Dispose();
            }
            WriteElementDesigner(bindCodeInfo, codeContext);
        }
        /// <summary>
        /// UI元素定义代码模板
        /// </summary>
        public static void WriteElementDesigner(BindCodeInfo bindCodeInfo, UIGenCodeContext codeContext)
        {
            var name = bindCodeInfo.Type;
            var scriptFilePath = codeContext.ElementPath + $"/{bindCodeInfo.Type}.Designer.cs";
            Directory.CreateDirectory(PathUtils.GetDirectoryPath(scriptFilePath));
            var writer = File.CreateText(scriptFilePath);
            var codeWriter = new FileCodeWriteKit(writer);
            var rootCode = new RootCode();
            WriteAutoGeneratedHeader(rootCode);
            rootCode
                .Using(nameof(UnityEngine))
                .Using("UnityEngine.UI")
                .Using(nameof(YokiFrame))
                .EmptyLine()
                .Namespace($"{codeContext.ScriptNamespace}.{codeContext.PanelName}{nameof(UIElement)}", scope =>
                {
                    scope.Class(name, string.Empty, true, false, classScope =>
                    {
                        //根据order排序
                        var sortList = bindCodeInfo.MemberDic.Values.OrderBy(info => info.order).ToList();
                        foreach (var bindInfo in sortList)
                        {
                            if (bindInfo.RepeatElement) continue;
                            if (!string.IsNullOrEmpty(bindInfo.Comment))
                            {
                                classScope.Custom("/// <summary>");
                                classScope.Custom("/// " + bindInfo.Comment);
                                classScope.Custom("/// </summary>");
                            }

                            classScope.Custom("[SerializeField]");
                            classScope.Custom($"public {bindInfo.Type} {bindInfo.Name};");

                            RecursionGen(bindInfo, codeContext);
                        }

                        classScope.EmptyLine();
                        classScope.CustomScope("public void Clear()", false, (property) =>
                        {
                            foreach (var bindInfo in bindCodeInfo.MemberDic.Values)
                            {
                                if (bindInfo.RepeatElement) continue;
                                if (bindInfo.Bind is BindType.Element or BindType.Component)
                                {
                                    property.Custom($"{bindInfo.Name}.Clear();");
                                }
                                property.Custom($"{bindInfo.Name} = default;");
                            }
                        });
                    });
                });

            rootCode.Gen(codeWriter);
            codeWriter.Dispose();
        }
        #endregion

        #region ComponentCodeTemplate
        /// <summary>
        /// UI组件代码模板
        /// </summary>
        public static void WriteComponent(BindCodeInfo bindCodeInfo, UIGenCodeContext codeContext)
        {
            var name = bindCodeInfo.Type;
            var scriptFilePath = codeContext.ComponentPath + $"/{name}.cs";
            if (!File.Exists(scriptFilePath))
            {
                Directory.CreateDirectory(PathUtils.GetDirectoryPath(scriptFilePath));
                var writer = File.CreateText(scriptFilePath);
                var codeWriter = new FileCodeWriteKit(writer);
                var rootCode = new RootCode()
                    .Custom("/****************************************************************************")
                    .Custom($"{DateTime.Now.Year}.{DateTime.Now.Month} {SystemInfo.deviceName}")
                    .Custom("****************************************************************************/")
                    .EmptyLine()
                    .Using(nameof(UnityEngine))
                    .Using("UnityEngine.UI")
                    .Using(nameof(YokiFrame))
                    .EmptyLine()
                    .Namespace(codeContext.ScriptNamespace, scope =>
                    {
                        scope.Class(name, nameof(UIComponent), true, false, fatherClass =>
                        {
                        });
                    });

                rootCode.Gen(codeWriter);
                codeWriter.Dispose();
            }
            WriteComponentDesigner(bindCodeInfo, codeContext);
        }
        /// <summary>
        /// UI组件定义代码模板
        /// </summary>
        public static void WriteComponentDesigner(BindCodeInfo bindCodeInfo, UIGenCodeContext codeContext)
        {
            var name = bindCodeInfo.Type;
            var scriptFilePath = codeContext.ComponentPath + $"/{bindCodeInfo.Type}.Designer.cs";

            Directory.CreateDirectory(PathUtils.GetDirectoryPath(scriptFilePath));
            var writer = File.CreateText(scriptFilePath);
            var codeWriter = new FileCodeWriteKit(writer);
            var rootCode = new RootCode();
            WriteAutoGeneratedHeader(rootCode);
            rootCode
                .Using(nameof(UnityEngine))
                .Using("UnityEngine.UI")
                .Using(nameof(YokiFrame))
                .EmptyLine()
                .Namespace(codeContext.ScriptNamespace, scope =>
                {
                    scope.Class(name, string.Empty, true, false, classScope =>
                    {
                        //根据order排序
                        var sortList = bindCodeInfo.MemberDic.Values.OrderBy(info => info.order).ToList();
                        foreach (var bindInfo in sortList)
                        {
                            if (bindInfo.Bind is BindType.Element)
                            {
                                Debug.LogWarning("Component组件下不持支定义Element元素");
                                bindCodeInfo.MemberDic.Remove(bindInfo.Name);
                                continue;
                            }
                            if (bindInfo.RepeatElement) continue;
                            if (!string.IsNullOrEmpty(bindInfo.Comment))
                            {
                                classScope.Custom("/// <summary>");
                                classScope.Custom("/// " + bindInfo.Comment);
                                classScope.Custom("/// </summary>");
                            }

                            classScope.Custom("[SerializeField]");
                            classScope.Custom($"public {bindInfo.Type} {bindInfo.Name};");

                            RecursionGen(bindInfo, codeContext, true);
                        }


                        classScope.EmptyLine();
                        classScope.CustomScope("public void Clear()", false, (property) =>
                        {
                            foreach (var bindInfo in bindCodeInfo.MemberDic.Values)
                            {
                                if (bindInfo.RepeatElement) continue;
                                if (bindInfo.Bind is BindType.Element or BindType.Component)
                                {
                                    property.Custom($"{bindInfo.Name}.Clear();");
                                }
                                property.Custom($"{bindInfo.Name} = default;");
                            }
                        });
                    });
                });

            rootCode.Gen(codeWriter);
            codeWriter.Dispose();
        }
        #endregion

        /// <summary>
        /// 递归生成元素和组件代码
        /// </summary>
        /// <param name="bindInfo"></param>
        /// <param name="codeContext"></param>
        private static void RecursionGen(BindCodeInfo bindInfo, UIGenCodeContext codeContext, bool isComponent = false)
        {
            //重复Element不用反复生成代码
            if (bindInfo.RepeatElement) return;
            var typeName = $"{nameof(bindInfo.Bind)}{bindInfo.Type}";
            if (!isComponent && bindInfo.Bind is BindType.Element)
            {
                if (!codeContext.AlreadyElementSet.Contains(typeName))
                {
                    codeContext.AlreadyElementSet.Add(typeName);
                    WriteElement(bindInfo, codeContext);
                }
            }
            else if (bindInfo.Bind is BindType.Component)
            {
                if (!codeContext.AlreadyElementSet.Contains(typeName))
                {
                    codeContext.AlreadyElementSet.Add(typeName);
                    WriteComponent(bindInfo, codeContext);
                }
            }
        }
    }

    /// <summary>
    /// UI代码生成上下文
    /// </summary>
    public class UIGenCodeContext
    {
        /// <summary>
        /// 面板名称
        /// </summary>
        public string PanelName;
        /// <summary>
        /// 元素路径
        /// </summary>
        public string ElementPath;
        /// <summary>
        /// 组件路径
        /// </summary>
        public string ComponentPath;
        /// <summary>
        /// 命名空间
        /// </summary>
        public string ScriptNamespace;
        /// <summary>
        /// 已生成的元素和组件集合
        /// </summary>
        public HashSet<string> AlreadyElementSet = new();
    }
}